settings:
  language: 'en'

guiMaterials:
  fillers:
    mainTheme: 'PURPLE_STAINED_GLASS_PANE'
    secondaryTheme: 'BLACK_STAINED_GLASS_PANE'
    successTheme: 'LIME_STAINED_GLASS_PANE'
  previousPageButton: 'PAPER'
  nextPageButton: 'PAPER'
  backToMarketButton: 'ARROW'
  currencyInfo: 'EMERALD'